name: Output Issues Information
on: issues
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output Github Context issue
              run: echo "${{ toJson(github.event) }}"